### PR TITLE
Fix Action fails if saving cache fails #53

### LINKED ISSUE #53: Action fails if saving cache fails
First of all thanks for this action 😄 

Today I had my [pre-commit job failing](https://github.com/s-weigand/flake8-nb/runs/1241477011), with the following error, which isn't fixable by rerunning the job:
```
Error: reserveCache failed: Cache already exists. Scope: refs/pull/80/merge, Key: pre-commit-2-b76e203571a33b83fd824866e8e8daaeda30555cba9e70eb155d9e5310e578b8-7365e065f5f4ed7e591c7e54ee4f8c40d559f8ff4d40fb8fc9eec5d1a9d2e11c, Version: 28cdb9f5496f334116f23e86f0063f5d3a9348c2e22425a33171e071aadada7e
```

My best guess is, that this caused by a corrupted cache, where a cache entry with the key exists, but `cache.restoreCache` is unable to restore it properly (maybe `on: push` and `on: pull_request` wanted to save the cache at the same time? 😵 ). 
So this might be a very rare and quite impossible to reproduce case.

Anyway, since the cache is nice and all, but not a key feature, IMHO it would be reasonable to catch errors caused by `cache.saveCache` and give users a warning ( `core.warning`), instead of letting it bubble up to `core.setFailed`.
https://github.com/pre-commit/action/blob/763fbafdffca49ae97893be3e08a1cf96f2af95f/index.js#L87

Also, there have been some [changes to `@actions/cache`](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md) since [version 0.2.1 which you use](https://github.com/pre-commit/action/blob/763fbafdffca49ae97893be3e08a1cf96f2af95f/package-lock.json#L6), so running `npm upgrade` might improve this action as well.

### PR DESCRIPTION
**Pull request by s-weigand**
This should fix #53, but as said before, the problem itself is most likely due to corruped cache, which makes testing it quite hard.
Wrapped saving cache in try-catch block, so the action itself shouldn't fail, if the caching fails.

### CODE REVIEW

**Comment by asottile** [comment]
one change per patch please, some parts of this are acceptable others are not -- I'm also planning to scrap/rewrite this at some point so I'm not sure if changing it now is a good idea

**Comment by s-weigand** [comment]
Ok sure, does keeping 470aac6 and ec0d6c4 sound reasonable to you?

**Comment by asottile** [comment]
> Ok sure, does keeping [470aac6](https://github.com/pre-commit/action/commit/470aac68535275c676ddfe26ea75c5ba2ca71dfd) and [ec0d6c4](https://github.com/pre-commit/action/commit/ec0d6c4913678e7018df9277a91562b36ce59dd0) sound reasonable to you?

yep seems fine, want to split those out?

**Comment by s-weigand** [comment]
Sure can do

File: index.js [hunk 1]
```diff
@@ -54,7 +54,20 @@ async function main() {
...
+        } catch (e) {
+            core.warning(
+                [
+                    "There was an error saving the pre-commit environments to cache:\n\n",
+                    `${e.message}\n\n`,
+                    "This only has performance implications and won't change the result of your pre-commit tests.\n",
+                    "If this problem persists on your default branch, you can try to fix it by editing your '.pre-commit-config.yaml'. ",
+                    "I.e. run 'pre-commit autoupdate' or simply add a blank line. ",
+                    "This will result in a different hash value and thus a different cache target.",
+                ].join("")
```
Comment (asottile) [inline index.js:68]: I think you can  use template strings as a multi line literal?

File: index.js [hunk 2]
```diff
@@ -54,7 +54,20 @@ async function main() {
...
     const ret = await exec.exec('pre-commit', args, {ignoreReturnCode: push});
     if (!restored) {
-        await cache.saveCache(cachePaths, cacheKey);
+        try {
+            await cache.saveCache(cachePaths, cacheKey);
+        } catch (e) {
+            core.warning(
+                [
+                    "There was an error saving the pre-commit environments to cache:\n\n",
+                    `${e.message}\n\n`,
```
Comment (asottile) [inline index.js:63]: is this a thing for all js exceptions?  I think this can be any type so it might not have a `.message`

File: index.js (hunk 1 above)
Comment (s-weigand) [reply index.js:68]: Yeah, but than you have an indentation issue, same as with python multiline string.
In python we have `textwrap.dedent` in the stdlib for that, but I don't know of something similar in node, without add a new dependency.
And manually breaking the indentation, by dedenting the lines inside the string to the very left, IMHO looks horrible.

File: index.js (hunk 2 above)
Comment (s-weigand) [reply index.js:63]: At least [`@actions/cache`](https://github.com/actions/toolkit/blob/af821474235d3c5e1f49cee7c6cf636abb0874c4/packages/cache/src/cache.ts#L131), throws proper errors.
But a quick browser console test, confirmed that `throw "some string"`, would work as well in js .... so that is something to watch out for, thanks for pointing it out 😄 
Quick test example:
```javascript
try{throw "foo"}catch(e){console.log(e)}
```

**Comment by dhimmel** [comment]
Have been getting `Error: reserveCache failed: Cache already exists` somewhat frequently, so thanks for this PR. Just wanted to check in, since would be great to have these errors resolved.

**Comment by s-weigand** [comment]
Didn't have that error again and forgot this PR 😅 
From my side, it is ready if @asottile is fine with it.

**Comment by asottile** [comment]
the comments aren't addressed

File: index.js (hunk 2 above)
Comment (s-weigand) [reply index.js:63]: `cache.saveCache` [throws an Error object](https://github.com/actions/toolkit/blob/af821474235d3c5e1f49cee7c6cf636abb0874c4/packages/cache/src/cache.ts#L170) which has the `message` property, so it should be fine.
But to be super safe this could be a ternary expression instead.
```js
e.message ? e.message : e
```

File: index.js (hunk 1 above)
Comment (s-weigand) [reply index.js:68]: When using a multiline string literal the only option to remove the indentation w/o adding an additional dependency I found would be to replace double spaces with an empty string `.replace(/  +/g, '')`. 
Would you prefer the format as it is now (only one linebreak after the first line) or rather formatted like the source?

Comment (s-weigand) [reply index.js]: Went with the source format, since replacing the double spaces and using line continuation would remove spaces between sentences.

File: index.js (hunk 2 above)
Comment (s-weigand) [reply index.js]: Well better safe than sorry, or having an `undefined` in the error message.

**Comment by s-weigand** [comment]
@asottile Should be fine now... I hope 😅

File: index.js [hunk 3]
```diff
@@ -54,7 +54,20 @@ async function main() {
...
     const ret = await exec.exec('pre-commit', args, {ignoreReturnCode: push});
     if (!restored) {
-        await cache.saveCache(cachePaths, cacheKey);
+        try {
+            await cache.saveCache(cachePaths, cacheKey);
+        } catch (e) {
+            core.warning(
+                `There was an error saving the pre-commit environments to cache:
+
+                ${e.message ? e.message : e}
```
Comment (asottile) [inline index.js:63]: `e.message || e`

File: index.js [hunk 4]
```diff
@@ -54,7 +54,20 @@ async function main() {
...
+
+                This only has performance implications and won't change the result of your pre-commit tests.
+                If this problem persists on your default branch, you can try to fix it by editing your '.pre-commit-config.yaml'.
+                I.e. run 'pre-commit autoupdate' or simply add a blank line.
+                This will result in a different hash value and thus a different cache target.`.replace(/  +/g, '')
```
Comment (asottile) [inline index.js:68]: `.replace(/^ +/gm, '')`

File: index.js [hunk 5]
```diff
@@ -54,7 +54,20 @@ async function main() {
...
+            await cache.saveCache(cachePaths, cacheKey);
+        } catch (e) {
+            core.warning(
+                `There was an error saving the pre-commit environments to cache:
+
+                ${e.message ? e.message : e}
+
+                This only has performance implications and won't change the result of your pre-commit tests.
+                If this problem persists on your default branch, you can try to fix it by editing your '.pre-commit-config.yaml'.
+                I.e. run 'pre-commit autoupdate' or simply add a blank line.
```
Comment (asottile) [inline index.js:67]: I think you actually mean `e.g.` -- though I try and avoid both of them because they're easy to confuse

File: index.js (hunk 4 above)
Comment (s-weigand) [reply index.js:68]: Hmmm just did a quick test in the chrome console (maybe `core.warning` behaves differently) but compare the output of 
```js
try {
            throw "foo";
        } catch (e) {
            console.warn(
                `There was an error saving the pre-commit environments to cache:

                ${e.message ? e.message : e}

                This only has performance implications and won't change the result of your pre-commit tests.

                If this problem persists on your default branch, you can try to fix it by editing your '.pre-commit-config.yaml'.
                I.e. run 'pre-commit autoupdate' or simply add a blank line.
                This will result in a different hash value and thus a different cache target.`.replace(/  +/g, '')
            );
        }
```
VS.
```js
try {
            throw "foo";
        } catch (e) {
            console.warn(
                `There was an error saving the pre-commit environments to cache:

                ${e.message ? e.message : e}

                This only has performance implications and won't change the result of your pre-commit tests.

                If this problem persists on your default branch, you can try to fix it by editing your '.pre-commit-config.yaml'.
                I.e. run 'pre-commit autoupdate' or simply add a blank line.
                This will result in a different hash value and thus a different cache target.`.replace(/^ +/g, '')
            );
        }
```
IMHO the `.replace(/  +/g, '')` version w/o the additional indents looks better.

File: index.js (hunk 5 above)
Comment (s-weigand) [reply index.js:67]: Oh yeah, I meant `e.g.` .... and ofc confused them. 😓 
Would replacing it with `For example` be fine?

File: index.js (hunk 4 above)
Comment (asottile) [reply index.js:68]: read carefully what I posted

File: index.js (hunk 3 above)
Comment (s-weigand) [reply index.js:63]: Done

File: index.js (hunk 4 above)
Comment (s-weigand) [reply index.js:68]: Damn missed the `m` flag never mind ... just me being a sleepy noob😞

File: index.js (hunk 5 above)
Comment (s-weigand) [reply index.js]: Replaced it with `For example try to`, hope that's fine.

**Review by asottile — APPROVED** [review]
